const musics = [
  {
    source: "src/Circles.mp3",
    title: "Circles",
    artist: "Post Malone",
    image: "images/HollywoodsBleeding.jpg",
    ident: "holybleed",
    color: "rgb(68, 68, 68)",
  },
  {
    source: "src/betty.mp3",
    title: "betty",
    artist: "Taylor Swift",
    image: "images/folklore.jpg",
    ident: "betty",
    color: "rgb(68, 68, 68)",
  },
  {
    source: "src/LostCause.mp3",
    title: "Lost Cause",
    artist: "Billie Eillish",
    image: "images/hte.jpg",
    ident: "hte",
    color: "#906D4D",
  },
  {
    source: "src/SongOfTime.mp3",
    title: "Song Of Time",
    artist: "Less Gravity",
    image: "images/sot.jpg",
    ident: "sot",
    color: "rgb(52, 100, 46)",
  },
  {
    source: "src/Starboy.mp3",
    title: "Starboy",
    artist: "The Weeknd",
    image: "images/Starboy.png",
    ident: "starboy",
    color: "#4d000e",
  },
  {
    source: "src/happinessisabutterfly.mp3",
    title: "Happiness is a butterfly",
    artist: "Lana Del Rey",
    image: "images/nfr.png",
    ident: "nfr",
    color: "#800d22",
  },
  {
    source: "src/Supercut.mp3",
    title: "Supercut",
    artist: "Lorde",
    image: "images/melodrama.webp",
    ident: "melodrama",
    color: "#0a3b8b",
  },
];

export {musics}